import { chromium } from 'playwright';
const OUT = process.argv[2];
const b = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const p = await (await b.newContext({ viewport: { width: 844, height: 390 }, deviceScaleFactor: 2 })).newPage();
const errs = [];
p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://localhost:5173/');
await p.waitForTimeout(1200);
await p.getByText('トレーニング').first().click();
await p.waitForTimeout(500);
await p.getByText('決定').first().click();
await p.waitForTimeout(2500);
await p.evaluate(() => { const s = __battle.sim.s; s.f[0].x = 7000; s.f[1].x = 9800; s.f[1].y = 3900; s.f[0].infGuard = 1; });
const r = await p.locator('.cbtn.atk').boundingBox();
const c = { x: r.x + r.width / 2, y: r.y + r.height / 2 };
await p.mouse.move(c.x, c.y); await p.mouse.down();
await p.mouse.move(c.x + 8, c.y + 4, { steps: 2 });
await p.waitForTimeout(350);
await p.screenshot({ path: `${OUT}/0-hold-inner-auto.png` });
await p.mouse.move(c.x - 70, c.y + 30, { steps: 4 });
await p.waitForTimeout(250);
await p.screenshot({ path: `${OUT}/1-free-aim.png` });
await p.mouse.move(c.x - 200, c.y - 30, { steps: 4 });
await p.waitForTimeout(250);
await p.screenshot({ path: `${OUT}/2-cancel.png` });
await p.mouse.up();
console.log(errs.join('\n') || 'no errors');
await b.close();
