// Generates src/core/trig-table.ts — integer trig tables baked at build time.
// Math.sin / Math.atan are implementation-approximated in ECMAScript, so the
// simulation must never call them at runtime (plan §9-5). Run: npm run gen:trig
import { writeFileSync } from 'node:fs';

const ANG = 1024; // binary angle units per full turn
const Q = 16384; // Q14 fixed point

const sin = [];
for (let i = 0; i < ANG; i++) sin.push(Math.round(Math.sin((i / ANG) * Math.PI * 2) * Q));

// atan(i/256) for i in 0..256, expressed in angle units (0..128)
const atan = [];
for (let i = 0; i <= 256; i++) atan.push(Math.round((Math.atan(i / 256) / (Math.PI * 2)) * ANG));

const fmt = (arr) => {
  const lines = [];
  for (let i = 0; i < arr.length; i += 16) lines.push('  ' + arr.slice(i, i + 16).join(', ') + ',');
  return lines.join('\n');
};

const out = `// AUTO-GENERATED by tools/gen-trig.mjs — do not edit.
// SIN_TABLE[a] = round(sin(a / ${ANG} * 2π) * ${Q})
export const SIN_TABLE = new Int32Array([
${fmt(sin)}
]);

// ATAN_TABLE[i] = round(atan(i / 256) / 2π * ${ANG})
export const ATAN_TABLE = new Int32Array([
${fmt(atan)}
]);
`;
writeFileSync(new URL('../src/core/trig-table.ts', import.meta.url), out);
console.log('wrote src/core/trig-table.ts');
